# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class DotenvxExtVault < Formula
  desc "🔐 manage envvault files (deprecated format)"
  homepage "https://github.com/dotenvx/dotenvx-ext-vault"
  url "https://github.com/dotenvx/dotenvx-ext-vault/archive/refs/tags/v0.3.2.tar.gz"
  sha256 "c978d7cdfefb66116740774cb419ab48e2a4b87c0bc65a494870692023be5414"
  license "BSD-3-Clause"

  on_macos do
    on_intel do
      url "https://github.com/dotenvx/dotenvx-ext-vault/releases/download/v0.3.2/dotenvx-ext-vault-0.3.2-darwin-amd64.tar.gz"
      sha256 "3a80faeade8e5c3ee7e9eb2251ef27456c53fd2875e7336ec62335e36d7cbcdc"
    end

    on_arm do
      url "https://github.com/dotenvx/dotenvx-ext-vault/releases/download/v0.3.2/dotenvx-ext-vault-0.3.2-darwin-arm64.tar.gz"
      sha256 "c7499fe61bf9379e505cd24abbb0a0312160fcab99c126fbd5713c907b05cf67"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotenvx/dotenvx-ext-vault/releases/download/v0.3.2/dotenvx-ext-vault-0.3.2-linux-amd64.tar.gz"
      sha256 "6af858b61ee76e994d795f3b250a0d8f6db78a90df9f5bf7552192c0149dcf6b"
    end

    on_arm do
      url "https://github.com/dotenvx/dotenvx-ext-vault/releases/download/v0.3.2/dotenvx-ext-vault-0.3.2-linux-arm64.tar.gz"
      sha256 "e001225f47df32a82cf81371c3ff2f8b10fd7fe36fbe01cf4432b257ed3bec0d"
    end
  end

  def install
    bin.install "dotenvx-ext-vault";
  end

  test do
    system bin/"dotenvx-ext-vault", "--version";
  end
end
