# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Dotenv < Formula
  desc "Better dotenv–from the creator of `dotenv`"
  homepage "https://github.com/dotenv-org/dotenv"
  url "https://github.com/dotenv-org/dotenv/archive/refs/tags/v0.2.13.tar.gz"
  sha256 "370c25b891c73c66e8c76fc7f61f18e3f1fc3dbf8d34efc8e2e1226c7a4c106a"

  on_macos do
    on_intel do
      url "https://github.com/dotenv-org/dotenv/releases/download/v0.2.13/dotenv-0.2.13-darwin-amd64.tar.gz"
      sha256 "623cfce0d9ce5fa3c8804f48728f6a11a98494ff13cbc37ef5591bea554a6b0f"
    end

    on_arm do
      url "https://github.com/dotenv-org/dotenv/releases/download/v0.2.13/dotenv-0.2.13-darwin-arm64.tar.gz"
      sha256 "de73a5a768b3fe0bd507ee9b765828bf99797a2910bce7e5c5ab993e20ff08df"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotenv-org/dotenv/releases/download/v0.2.13/dotenv-0.2.13-linux-amd64.tar.gz"
      sha256 "9e7e7a79e3e4e898ddb7d41764caa017d27a277d773e6988f624af6cc699aea3"
    end

    on_arm do
      url "https://github.com/dotenv-org/dotenv/releases/download/v0.2.13/dotenv-0.2.13-linux-arm64.tar.gz"
      sha256 "385a03e46f2b885e2099aad32df420e695220b539f89902526f9f53eed1640da"
    end
  end

  def install
    bin.install "dotenv"; bin.install_symlink "dotenv" => "git-dotenv";bin.install "dotenv2"; bin.install_symlink "dotenv2" => "git-dotenv2"
  end

  test do
    system bin/"dotenv", "--version";system bin/"dotenv2", "--version";
  end
end
