# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class DotenvxExtVault < Formula
  desc "🔐 manage envvault files"
  homepage "https://github.com/dotenvx/dotenvx-ext-vault"
  url "https://github.com/dotenvx/dotenvx-ext-vault/archive/refs/tags/v0.2.1.tar.gz"
  sha256 "099a160e7f1cfb9d99993d4e10d947eeeacd230c6afe9c28d18b735a34f2b411"
  license "BSD-3-Clause"

  on_macos do
    on_intel do
      url "https://github.com/dotenvx/dotenvx-ext-vault/releases/download/v0.2.1/dotenvx-ext-vault-0.2.1-darwin-amd64.tar.gz"
      sha256 "776387d9b1cab1bdb8e969c8c9b02122f4cfa2dcb220c95566aab5038f8cb605"
    end

    on_arm do
      url "https://github.com/dotenvx/dotenvx-ext-vault/releases/download/v0.2.1/dotenvx-ext-vault-0.2.1-darwin-arm64.tar.gz"
      sha256 "a13752624dea0f16f7eb3b1ee7bcf463795b91f2c9ec80ea31037c29caff2064"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotenvx/dotenvx-ext-vault/releases/download/v0.2.1/dotenvx-ext-vault-0.2.1-linux-amd64.tar.gz"
      sha256 "cb452a8236ad93f95e4f0811416db968c7d25a95e389cee928298c0d69c3e059"
    end

    on_arm do
      url "https://github.com/dotenvx/dotenvx-ext-vault/releases/download/v0.2.1/dotenvx-ext-vault-0.2.1-linux-arm64.tar.gz"
      sha256 "eb4aaac4356e1407cd78860e541a4195d8969412d93eae2583165ff6c5ca251d"
    end
  end

  def install
    bin.install "dotenvx-ext-vault";
  end

  test do
    system bin/"dotenvx-ext-vault", "--version";
  end
end
