# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Dotenv < Formula
  desc "“better dotenv“ from the creator of `dotenv`"
  homepage "https://github.com/dotenv-org/dotenv"
  url "https://github.com/dotenv-org/dotenv/archive/refs/tags/v0.2.5.tar.gz"
  sha256 "03e4c942412ac2cfa41137c95c8b44b347472ea8c548f29e2e3a33889c48a66b"

  on_macos do
    on_intel do
      url "https://github.com/dotenv-org/dotenv/releases/download/v0.2.5/dotenv-0.2.5-darwin-amd64.tar.gz"
      sha256 "e655649be76ab8b5f3ea32a0b173d8667b6aca6c0a07e106dc664c741f0a4a2c"
    end

    on_arm do
      url "https://github.com/dotenv-org/dotenv/releases/download/v0.2.5/dotenv-0.2.5-darwin-arm64.tar.gz"
      sha256 "46b286c9fc83705632e8c28c9cfa39489530a8cb868b83afbaddb4472ee99095"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotenv-org/dotenv/releases/download/v0.2.5/dotenv-0.2.5-linux-amd64.tar.gz"
      sha256 "be3266fb6fe60919e9e84dd5a984bd7e4ff284cc58b4de92b84cce7b23dff3a7"
    end

    on_arm do
      url "https://github.com/dotenv-org/dotenv/releases/download/v0.2.5/dotenv-0.2.5-linux-arm64.tar.gz"
      sha256 "282cfbea363cedd8e63f1f900be206099a7c5429ce8595a168cbb5e71286055c"
    end
  end

  def install
    bin.install "dotenv"; bin.install_symlink "dotenv" => "git-dotenv"
  end

  test do
    system bin/"dotenv", "--version"
  end
end
