# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class DotenvxExtVault < Formula
  desc "🔐 manage envvault files"
  homepage "https://github.com/dotenvx/dotenvx-ext-vault"
  url "https://github.com/dotenvx/dotenvx-ext-vault/archive/refs/tags/v0.2.0.tar.gz"
  sha256 "884dde2548111e16a84640a0b7c535780104bb2dc70c9f5d4b2277d4f3c8b080"
  license "BSD-3-Clause"

  on_macos do
    on_intel do
      url "https://github.com/dotenvx/dotenvx-ext-vault/releases/download/v0.2.0/dotenvx-ext-vault-0.2.0-darwin-amd64.tar.gz"
      sha256 "206241269b1e61ab190b07b25db69e154ea9b1deb8b356e14c42de1ea7b8b3db"
    end

    on_arm do
      url "https://github.com/dotenvx/dotenvx-ext-vault/releases/download/v0.2.0/dotenvx-ext-vault-0.2.0-darwin-arm64.tar.gz"
      sha256 "75b1274bb2fd7f6fc0e1ad9f3845e6827b9d175268ae6cdb06394c4043f835f7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotenvx/dotenvx-ext-vault/releases/download/v0.2.0/dotenvx-ext-vault-0.2.0-linux-amd64.tar.gz"
      sha256 "48ca80b6c8ba4e4bb1b890e72f5a4b74a9018cfe6a5661e3aa8bea8930d8306e"
    end

    on_arm do
      url "https://github.com/dotenvx/dotenvx-ext-vault/releases/download/v0.2.0/dotenvx-ext-vault-0.2.0-linux-arm64.tar.gz"
      sha256 "83398333e8d587911e63509e6dc42062b09c42999e946b436e7c0f6e54fa48f3"
    end
  end

  def install
    bin.install "dotenvx-ext-vault";
  end

  test do
    system bin/"dotenvx-ext-vault", "--version";
  end
end
