# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class DotenvxExtHub < Formula
  desc "🚫 deprecated: to be replaced by [dotenvx pro]"
  homepage "https://github.com/dotenvx/dotenvx-ext-hub"
  url "https://github.com/dotenvx/dotenvx-ext-hub/archive/refs/tags/v0.2.3.tar.gz"
  sha256 "f001ab487d161b1609303baadbb138c41ac5c75f379ea819945861fc0836a7b7"
  license "BSD-3-Clause"

  on_macos do
    on_intel do
      url "https://github.com/dotenvx/dotenvx-ext-hub/releases/download/v0.2.3/dotenvx-ext-hub-0.2.3-darwin-amd64.tar.gz"
      sha256 "44fb63f08679308906c89e6cc149d9ba53d509b6ef5f6de627df28898a798018"
    end

    on_arm do
      url "https://github.com/dotenvx/dotenvx-ext-hub/releases/download/v0.2.3/dotenvx-ext-hub-0.2.3-darwin-arm64.tar.gz"
      sha256 "8af6983834a6cf8baf6199399583910a58c9a56d165a4b635ca44ebd66d507fa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotenvx/dotenvx-ext-hub/releases/download/v0.2.3/dotenvx-ext-hub-0.2.3-linux-amd64.tar.gz"
      sha256 "f5388f301dbf85a84f6a7033ad32b5c126456c717e7212c90372e934972c0ab4"
    end

    on_arm do
      url "https://github.com/dotenvx/dotenvx-ext-hub/releases/download/v0.2.3/dotenvx-ext-hub-0.2.3-linux-arm64.tar.gz"
      sha256 "48b7821ab0b9473456f17599784e673166a0b0d1c323199b63e33df40e242441"
    end
  end

  def install
    bin.install "dotenvx-ext-hub";
  end

  test do
    system bin/"dotenvx-ext-hub", "--version";
  end
end
