# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Dotenvx < Formula
  desc "Better dotenv–from the creator of `dotenv`"
  homepage "https://github.com/dotenvx/dotenvx"
  url "https://github.com/dotenvx/dotenvx/archive/refs/tags/v0.31.1.tar.gz"
  sha256 "849e7fdb6d54c927650ab974ccebd4f8d4dcdd10da179c431c72d2ac1ddfb80f"
  license "BSD-3-Clause"

  on_macos do
    on_intel do
      url "https://github.com/dotenvx/dotenvx/releases/download/v0.31.1/dotenvx-0.31.1-darwin-amd64.tar.gz"
      sha256 "a1877189e151bef5c8e31813b9bfda939fecb1d397557d41496873a02035c2ae"
    end

    on_arm do
      url "https://github.com/dotenvx/dotenvx/releases/download/v0.31.1/dotenvx-0.31.1-darwin-arm64.tar.gz"
      sha256 "fcd14f765e9fee67de591a38b6fc1ef0dabb6981a4a406e146d9fe522f2d3eef"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotenvx/dotenvx/releases/download/v0.31.1/dotenvx-0.31.1-linux-amd64.tar.gz"
      sha256 "60f42bc60e660d444b9ac3f32e5fc5198cc5d890b1e4f53aca1abf78256033b5"
    end

    on_arm do
      url "https://github.com/dotenvx/dotenvx/releases/download/v0.31.1/dotenvx-0.31.1-linux-arm64.tar.gz"
      sha256 "eb35f7f3725ce53a31884f95f317d4a5139c7751e2741b71b5d6a6827cf80e6f"
    end
  end

  def install
    bin.install "dotenvx"; bin.install_symlink "dotenvx" => "git-dotenvx";
  end

  test do
    system bin/"dotenvx", "--version";
  end
end
