# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class DotenvxPro < Formula
  desc "Dotenvx-pro cli"
  homepage "https://github.com/dotenvx/dotenvx-pro"
  url "https://api.github.com/repos/dotenvx/dotenvx-pro/tarball/v0.1.2"
  sha256 "8d77d7096b6a25add7e72c5436bb6b0b16041727a449617c0edf00bd35b4753c"

  on_macos do
    on_intel do
      url "https://github.com/dotenvx/dotenvx-pro/releases/download/v0.1.2/dotenvx-pro-0.1.2-darwin-amd64.tar.gz"
      sha256 "09420f14f4a03278262e12c01684260dfe1e3a2072e267ce544b106d03da873e"
    end

    on_arm do
      url "https://github.com/dotenvx/dotenvx-pro/releases/download/v0.1.2/dotenvx-pro-0.1.2-darwin-arm64.tar.gz"
      sha256 "55d8ed50a4a1fc0866818791420086ee44bfa8d0890c8d1622f0048db220dd84"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotenvx/dotenvx-pro/releases/download/v0.1.2/dotenvx-pro-0.1.2-linux-amd64.tar.gz"
      sha256 "3594fc02e5b2019d7318e40dd036ee9efbd205f58358a6861363d08fa4988b02"
    end

    on_arm do
      url "https://github.com/dotenvx/dotenvx-pro/releases/download/v0.1.2/dotenvx-pro-0.1.2-linux-arm64.tar.gz"
      sha256 "d3e026584a2e5a4e3ada021472bce3edbfd9f169d1b1551b9beadb0dd34f2bdf"
    end
  end

  def install
    bin.install "dotenvx-pro";
  end

  test do
    system bin/"dotenvx-pro", "--version";
  end
end
