# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class DotenvxPro < Formula
  desc "Dotenvx-pro cli"
  homepage "https://github.com/dotenvx/dotenvx-pro"
  url "https://github.com/dotenvx/dotenvx-pro/archive/refs/tags/v0.11.0.tar.gz"
  sha256 "609e3f2c580a8a8e952611383be56f28616f1f49cf4c0b5381307948604fca9f"

  on_macos do
    on_intel do
      url "https://github.com/dotenvx/dotenvx-pro/releases/download/v0.11.0/dotenvx-pro-0.11.0-darwin-amd64.tar.gz"
      sha256 "d232a204c9ea16f4666c678d7f47136ffc63137c942ca346dfb3e3874c539f45"
    end

    on_arm do
      url "https://github.com/dotenvx/dotenvx-pro/releases/download/v0.11.0/dotenvx-pro-0.11.0-darwin-arm64.tar.gz"
      sha256 "8253fbab13fb974d8f523e94eaf15abe8d2f56ba90f001abd17c9da703c18056"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotenvx/dotenvx-pro/releases/download/v0.11.0/dotenvx-pro-0.11.0-linux-amd64.tar.gz"
      sha256 "cffe8feffe1d4033a94f2f03201a2c325acd78e8c660f94f91293300d97d4581"
    end

    on_arm do
      url "https://github.com/dotenvx/dotenvx-pro/releases/download/v0.11.0/dotenvx-pro-0.11.0-linux-arm64.tar.gz"
      sha256 "82d00d55cb90ce828b5264824de4216746fd460ea8c56c3fe90640040d4308d7"
    end
  end

  def install
    bin.install "dotenvx-pro";
  end

  test do
    system bin/"dotenvx-pro", "--version";
  end
end
