# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class DotenvxExtHub < Formula
  desc "🚫 deprecated: to be replaced by [dotenvx pro]"
  homepage "https://github.com/dotenvx/dotenvx-ext-hub"
  url "https://github.com/dotenvx/dotenvx-ext-hub/archive/refs/tags/v0.3.0.tar.gz"
  sha256 "3df24a60d78ce6fe495c1407b3d4ace218c6acb93a25481cb859f3bccdfd3ad2"
  license "BSD-3-Clause"

  on_macos do
    on_intel do
      url "https://github.com/dotenvx/dotenvx-ext-hub/releases/download/v0.3.0/dotenvx-ext-hub-0.3.0-darwin-amd64.tar.gz"
      sha256 "34e18e5ccb41d3514d538c04ad1a25b12d6d659913d123311351453357b2d9c7"
    end

    on_arm do
      url "https://github.com/dotenvx/dotenvx-ext-hub/releases/download/v0.3.0/dotenvx-ext-hub-0.3.0-darwin-arm64.tar.gz"
      sha256 "febad933dc5c9b049f2ec8fe4f923d76883514793ae2e5ccf8d7b337265e4a4d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotenvx/dotenvx-ext-hub/releases/download/v0.3.0/dotenvx-ext-hub-0.3.0-linux-amd64.tar.gz"
      sha256 "cb98c79c1103424e22e695509c77e05173116172aad4af676b0b38aec57a0c93"
    end

    on_arm do
      url "https://github.com/dotenvx/dotenvx-ext-hub/releases/download/v0.3.0/dotenvx-ext-hub-0.3.0-linux-arm64.tar.gz"
      sha256 "eb6dedf8753e96f6cb7b3ec6ba13c5b889dd0090b4245cc9d8c186b8b878e38d"
    end
  end

  def install
    bin.install "dotenvx-ext-hub";
  end

  test do
    system bin/"dotenvx-ext-hub", "--version";
  end
end
