# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Dotenvx < Formula
  desc "Better dotenv–from the creator of `dotenv`"
  homepage "https://github.com/dotenvx/dotenvx"
  url "https://github.com/dotenvx/dotenvx/archive/refs/tags/v1.14.0.tar.gz"
  sha256 "0b101342171c6f1a24843596da03323c51d1211a82473941f59670f36ac54869"
  license "BSD-3-Clause"

  on_macos do
    on_intel do
      url "https://github.com/dotenvx/dotenvx/releases/download/v1.14.0/dotenvx-1.14.0-darwin-amd64.tar.gz"
      sha256 "c61ff1dbddc7079df629059a13161b9d3bba1932f047118418d0c4aecedfc064"
    end

    on_arm do
      url "https://github.com/dotenvx/dotenvx/releases/download/v1.14.0/dotenvx-1.14.0-darwin-arm64.tar.gz"
      sha256 "b84e805ef75d57ce008ed656950862b9852f7f92370adf73fe63b0a335523030"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotenvx/dotenvx/releases/download/v1.14.0/dotenvx-1.14.0-linux-amd64.tar.gz"
      sha256 "21c465a6f43adc238854bb187fa8352ee953225ae1a51a003cceae00e01e5ab4"
    end

    on_arm do
      url "https://github.com/dotenvx/dotenvx/releases/download/v1.14.0/dotenvx-1.14.0-linux-arm64.tar.gz"
      sha256 "b162619a00ca2bc73d9fe2e9e35da8a04e937d34b9a9dc73461f577d101d6c9e"
    end
  end

  def install
    bin.install "dotenvx"; bin.install_symlink "dotenvx" => "git-dotenvx";
  end

  test do
    system bin/"dotenvx", "--version";
  end
end
