# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class GitDotenv < Formula
  desc "More secure, standalone, cross-platform dotenv - from the creator of dotenv"
  homepage "https://github.com/dotenv-org/git-dotenv"
  url "https://github.com/dotenv-org/git-dotenv/archive/refs/tags/v0.1.9.tar.gz"
  sha256 "1ea001673d53be1cb89b2ce4cca765cc437d1cbe90d3d27aadcab0360bcf854e"

  on_macos do
    on_intel do
      url "https://github.com/dotenv-org/git-dotenv/releases/download/v0.1.9/git-dotenv-0.1.9-darwin-amd64.tar.gz"
      sha256 "243b16f7d58b7e88893c3412b84f62a06b67d4f25b7b192a1156f63fe80d95a4"
    end

    on_arm do
      url "https://github.com/dotenv-org/git-dotenv/releases/download/v0.1.9/git-dotenv-0.1.9-darwin-arm64.tar.gz"
      sha256 "0602c2774191b4af1568132107958d55cc6ed49c630072bfb6e49c6d4b7de5ed"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotenv-org/git-dotenv/releases/download/v0.1.9/git-dotenv-0.1.9-linux-amd64.tar.gz"
      sha256 "753fe1bc7037ae94e833ee0702981d71edeaa757ec17fd74b892212fead30e2a"
    end

    on_arm do
      url "https://github.com/dotenv-org/git-dotenv/releases/download/v0.1.9/git-dotenv-0.1.9-linux-arm64.tar.gz"
      sha256 "7a8b210405780de2c3a50b0004c11068a54904499236c3741040db1bbfd2cb87"
    end
  end

  def install
    bin.install "git-dotenv"
  end

  test do
    system bin/"git-dotenv", "--version"
  end
end
