# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class GitDotenv < Formula
  desc "More secure, standalone, cross-platform dotenv - from the creator of dotenv"
  homepage "https://github.com/dotenv-org/git-dotenv"
  url "https://github.com/dotenv-org/git-dotenv/archive/refs/tags/v0.1.16.tar.gz"
  sha256 "d209c75d8d2b7c2ce97a2dda634d583c55a750ea73faa3458e27982fbfcc8452"

  on_macos do
    on_intel do
      url "https://github.com/dotenv-org/git-dotenv/releases/download/v0.1.16/git-dotenv-0.1.16-darwin-amd64.tar.gz"
      sha256 "17ec21b984a4631f58f742f2a2a06969288742231197b24072ae779006674ea7"
    end

    on_arm do
      url "https://github.com/dotenv-org/git-dotenv/releases/download/v0.1.16/git-dotenv-0.1.16-darwin-arm64.tar.gz"
      sha256 "7e2e0420e869731b19309beb205fff3b74ffa72b7fcf7c5302903f88343a9fd1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotenv-org/git-dotenv/releases/download/v0.1.16/git-dotenv-0.1.16-linux-amd64.tar.gz"
      sha256 "70b3430ffcdc3f60567f1fa93ba8921f7f87efe1125d5a7c4e629846a6aaadec"
    end

    on_arm do
      url "https://github.com/dotenv-org/git-dotenv/releases/download/v0.1.16/git-dotenv-0.1.16-linux-arm64.tar.gz"
      sha256 "af32aaadb929733c97a3a4fc649642316b9fd310edee607d5f69dfbff3738685"
    end
  end

  def install
    bin.install "git-dotenv"
  end

  test do
    system bin/"git-dotenv", "--version"
  end
end
