#!/usr/bin/env bash

set -ex

brew update
# register the current repo as a tap
brew tap dotenvx/brew "$(pwd)"
# now install from the tap
brew install dotenvx/brew/dotenvx
dotenvx --version
dotenvx help
